# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---

include:
  - board: seeeduino_xiao_ble
    shield: hexaboard
  - board: seeeduino_xiao_ble
    shield: hexaboard
    cmake-args: -DCONFIG_ZMK_BLE=n -DKEYMAP_FILE=./hexaboard.keymap
    artifact-name: xiaoble_without_ble
  - board: seeeduino_xiao_rp2040
    shield: hexaboard
    cmake-args: -DKEYMAP_FILE=../../config/hexaboard.keymap

# include:
#   - board: seeeduino_xiao_ble
#     shield: settings_reset
#   - board: seeeduino_xiao_ble
#     shield: hexaboard
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: hexaboard_xiao_ble
#   - board: seeeduino_xiao_rp2040
#     shield: hexaboard
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: seeeduino_xiao_rp2040
